#!/bin/bash
#########################################
#Function:    Auto_install_maya 
#Usage:       su root & bash  Auto_install_maya.sh
#Company:     MOREVFX.IT
#Version:     1.2
#########################################

maya2018_install()
{
#卸载已安装早期版本的 AdLM for Linux，
if [ rpm -qa | egrep 'adlm' ];then
      rpm -e adlm*
fi
cd $maya_rpm_path
rpm -ivh Maya2018_64-2018.0-#.x86_64.rpm adlmapps11-11.0.15-0.x86_64.rpm adlmflexnetclient-14.#.x86_64.rpm
#若要同时安装 Maya 与 Mudbox，请输入：rpm -ivh --force Maya2018_64-2018.0-#.x86_64.rpm adlmapps11-11.0.15-0.x86_64.rpm adlmflexnetclient-14.#.x86_64.rpm 


#创建 License相关文件
if [ ! -f "/var/flexlm/maya.lic" ];then
echo "MAYA_LICENSE_METHOD=network" >/usr/autodesk/maya2018/bin/License.env
echo "SERVER mlic.more.com 0" >/var/flexlm/maya.lic
echo "USE_SERVER" >>/var/flexlm/maya.lic
fi
#检查OpenGL 驱动程序
if [ ! -f "/usr/bin/glxinfo" ];then
      yum install glx-utils -yum
fi
#检查Maya 2018 将所需的 libXm.so.3 库
if [ ! -h "/usr/autodesk/maya2018/lib/libXm.so" ];then
      ln -s /usr/autodesk/maya2018/lib/libXm.so /usr/autodesk/maya2018/lib/libXm.so.3
fi
#将 /opt/Autodesk/Adlm/R14/lib64/ 添加到 LD_LIBRARY_PATH，为此会话设置共享库
export LD_LIBRARY_PATH=/opt/Autodesk/Adlm/R14/lib64/
#注册 Maya2018
/usr/autodesk/maya2018/bin/adlmreg -i N 657J1 657J1 2018.0.0.F 666-69696969 /var/opt/Autodesk/Adlm/Maya2018/MayaConfig.pit >/tmp/maya2018_install.log

Maya_Isinstalled=$(grep "succeeded" /tmp/maya2018_install.log)
if [ -n "$Maya_Isinstalled" ];then
      exit_script "maya2018 install succeeded"
    fi

}
maya2018_install
