#!/bin/bash
#########################################
#Function:    Auto_install_All_Software_for_Cobbler
#Usage:       rc.local
#Company:     MOREVFX.IT
#Version:     1.0
#########################################



mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak
\cp /media/X/TD/IT/IT-SYSTEM/Yum_repo/centos7/CentOS-Base.repo /etc/yum.repos.d/
yum clean all
yum -y update -y
yum -y install qt
yum -y install libsss* sssd*
yum -y install ncurses-devel
yum -y install qt-devel openssl-devel
yum -y install hmaccalc zlib-devel binutils-devel elfutils-libelf-dev
yum -y install lm_sensors 
yum -y update glibc\* yum\* rpm\* python\*
yum -y install ntfs-3g
yum -y install python-pyside
yum -y install flash-plugin
yum -y install icedtea-web
yum -y install vlc smplayer ffmpeg HandBrake-{gui,cli}
yum -y install libdvdcss gstreamer{,1}-plugins-ugly gstreamer-plugins-bad-nonfree gstreamer1-plugins-bad-freeworld
yum -y install shadowsocks-qt5 qt5-qtbase-devel
yum -y install libpng*
yum -y install redhat-lsb
yum -y install libtiff*
yum -y install authconfig-gtk
yum -y install yp-tools ypbind rpcbind
yum -y install gimp
yum -y install gcc csh gamin  tcsh xorg-x11-fonts-ISO8859-1-100dpi 
yum -y install liberation-mono-fonts liberation-fonts-common liberation-sans-fonts liberation-serif-fonts xorg-x11-fonts-ISO8859-1-75dpi 
yum -y install glib libgnomeui-devel mesa-libGLw libXp libXp-devel
yum -y install audiofile audiofile-devel e2fsprogs-libs
yum -y install libX11-devel libxml2-devel libxslt-devel freetype-devel flex bison
yum -y install tunctl
yum -y install tree telnet dos2unix sysstat lrzsz -y
yum -y install -y bash-completion
yum -y install cmake vim wget lrzsz htop
yum -y install fusioninventory-agent fusioninventory-agent-task-inventory
yum -y install tigervnc-server

#chrony 时间同步
timedatectl set-timezone Asia/Shanghai
sed -i 's/0.centos.pool.ntp.org/ntp.more.com/' /etc/chrony.conf
sed -i 's/1.centos.pool.ntp.org/time.more.com/' /etc/chrony.conf


#update kernel
#yum -y install kernel-ml-devel kernel-ml

#mount X,Y,P,D,E   如果是工作站，请把nolock，删除 
#echo "mount -t nfs -o nolock,noatime,nodiratime 192.168.16.10:/export/MORE_ORACLE /media/X" >>/etc/rc.d/rc.local
#echo "mount -t nfs -o nolock,noatime,nodiratime 192.168.17.10:/mnt/Freenas/Work /media/Y" >>/etc/rc.d/rc.local
#echo "mount -t nfs -o nolock,noatime,nodiratime 192.168.16.10:/export/MORE_ORACLE/TD/PLE2 /media/P" >>/etc/rc.d/rc.local
#sed -i '/#Domain/a\Domain = more.com'/etc/idmapd.conf
#chmod +x /etc/rc.d/rc.local
#chmod +x /etc/rc.local
#bash /etc/rc.d/rc.local

# disable usb wikif bluetooth connect
rm -rf /lib/modules/*/kernel/drivers/usb/
rm -rf /lib/modules/*/kernel/drivers/net/wireless
rm -rf /lib/modules/*/kernel/drivers/bluetooth

#join domian for NIS
echo "NISDOMAIN=more" >> /etc/sysconfig/network
echo "ad1.more.com" >> /etc/sysconfig/network
authconfig --enablenis --nisdomain=more --nisserver=ad1.more.com --passalgo=md5 --enablemkhomedir --update

#  Perp install NVIDIA drivers
#mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r).img.bak
#dracut -v /boot/initramfs-$(uname -r).img $(uname -r)
#sed -i 's/blacklist nvidiafb/blacklist nouveau/g' /usr/lib/modprobe.d/dist-blacklist.conf
#systemctl set-default multi-user.target
#\cp /media/Y/BAK-Y/linux_backup/drivers/NVIDIA-Linux-x86*.run /home
#chmod 755 /home/NVIDIA-Linux-*.run 
#\cp /media/X/TD/IT/IT-SYSTEM/init/Install_Nvidia_Drivers.sh /home
#chmod +x /home/Install_Nvidia_Drivers.sh
#echo "/home/Install_Nvidia_Drivers.sh" >>/etc/rc.d/rc.local

#桌面快捷方式与系统环境变量
#\cp /media/X/TD/IT/IT-SYSTEM/init/MORE_desktop/skel/ /etc/skel/
#\cp /media/X/TD/IT/IT-SYSTEM/init/MORE_desktop/bashrc /etc/bashrc
\cp -f /media/X/TD/IT/IT-SYSTEM/init/MORE_desktop/*.desktop /usr/share/applications/

#add local Render user 
groupadd -g 621001 PPM_Manager
useradd -u 1120146 -g 621001 -G PPM_Manager render
echo "xxxx" | passwd --stdin render
sed -i '/^root/a\render  ALL=(ALL)   NOPASSWD: ALL' /etc/sudoers

#auto login render
sed -i '/daemon/a\AutomaticLogin=render' /etc/gdm/custom.conf
sed -i '/daemon/a\AutomaticLoginEnable=true' /etc/gdm/custom.conf

#vnc server
\cp /lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@\:2.service
\cp -r /media/X/TD/IT/IT-SYSTEM/Linux_conf/vnc_render_conf /home/render/.vnc
chown -R render:render /home/render/.vnc
sed -i '/ExecStart/s/<USER>/render/g' /etc/systemd/system/vncserver@\:2.service
sed -i '/PIDFile/s/<USER>/render/g' /etc/systemd/system/vncserver@\:2.service
sed -i 's/#vnc_password/vnc_password /g' /etc/libvirt/qemu.conf
sed -i 's/XYZ12345/'xxxxx' /g' /etc/libvirt/qemu.conf
\rm -rf /tmp/.X11-unix/*
systemctl daemon-reload
systemctl enable vncserver@\:2.service
systemctl start vncserver@\:2.service

#%addon com_redhat_kdump --enable --reserve-mb='auto'

#INSTALL MAYA2016
cd /media/Y/BAK-Y/linux_backup/software/maya2016_linux/Autodesk_Maya_2016_EXT1_SP6_EN_Linux_64bit/
rpm -ivh Maya2016_64-2016.0-2775.x86_64.rpm
rpm -ivh adlmapps11-11.0.15-0.x86_64.rpm
rpm -ivh adlmflexnetclient-11.0.15-0.x86_64.rpm
echo "MAYA_LICENSE=unlimited " >/usr/autodesk/maya2016/bin/License.env
echo "MAYA_LICENSE_METHOD=network" >>/usr/autodesk/maya2016/bin/License.env
echo 'SERVER mlic.more.com 0' >/var/flexlm/maya.lic
echo 'USE_SERVER' >>/var/flexlm/maya.lic
export LD_LIBRARY_PATH=/opt/Autodesk/Adlm/R11/lib64/
/usr/autodesk/maya2016/bin/adlmreg -i N 657h1 657h1 2016.0.0.f 666-69696969 /var/opt/Autodesk/Adlm/Maya2016/MayaConfig.pit 
\cp /lib64/libssh2.so.1 /opt/Autodesk/Adlm/R11/lib64/
\cp /lib64/libldap-2.4.so.2 /opt/Autodesk/Adlm/R11/lib64/
\cp /lib64/libssl.so.10 /opt/Autodesk/Adlm/R11/lib64/
\cp /lib64/libcrypto.so.10 /opt/Autodesk/Adlm/R11/lib64/
\cp /media/X/TD/IT/IT-SYSTEM/Autodesk_Crack/Linux/2016/libadlmint.so.11.0.15 /usr/autodesk/maya2016/lib/

#INSTALL MAYA2018
cd /media/Y/BAK-Y/linux_backup/software/maya2018_linux/Autodesk_Maya_2018_4_Update_Linux_64bit/
rpm -ivh Maya2018_64-2018.0-7413.x86_64.rpm
rpm -Uvh adlmapps14-14.0.23-0.x86_64.rpm
rpm -Uvh adlmflexnetclient-14.0.23-0.x86_64.rpm
echo "MAYA_LICENSE=657j1 " >/usr/autodesk/maya2018/bin/License.env
echo "MAYA_LICENSE_METHOD=network" >>/usr/autodesk/maya2018/bin/License.env
echo 'SERVER mlic.more.com 0' >/var/flexlm/maya.lic
echo 'USE_SERVER' >>/var/flexlm/maya.lic
export LD_LIBRARY_PATH=/opt/Autodesk/Adlm/R14/lib64/
/usr/autodesk/maya2018/bin/adlmreg -i N 657j1 657j1 2018.0.0.f 666-69696969 /var/opt/Autodesk/Adlm/Maya2018/MayaConfig.pit 
\cp /media/X/TD/IT/IT-SYSTEM/Autodesk_Crack/Linux/2018/libadlmint.so.14.0.23 /usr/autodesk/maya2018/lib/

#MAYA图标
rm -rf /usr/share/applications/Autodesk-Maya2016.desktop
rm -rf /usr/share/applications/Autodesk-Maya2018.desktop
sed -i 's/\/usr\/autodesk\/maya/\/usr\/autodesk\/maya2016/' /usr/autodesk/maya2016/desktop/Autodesk-Maya.desktop
sed -i 's/\/usr\/autodesk\/maya/\/usr\/autodesk\/maya2018/' /usr/autodesk/maya2018/desktop/Autodesk-Maya.desktop
ln -s /usr/autodesk/maya2016/desktop/Autodesk-Maya.desktop /usr/share/applications/Autodesk-Maya2016.desktop
ln -s /usr/autodesk/maya2018/desktop/Autodesk-Maya.desktop /usr/share/applications/Autodesk-Maya2018.desktop

# /usr/share/applications
#rv 安装后开启rv  后要指一下lic文件，放在/usr/rv与/home/ 目录下
\cp -rf /media/X/TD/IT/IT-SYSTEM/Maya/Linux/rv7/rv /usr/local
ln -s /usr/local/rv/bin/rv /usr/local/sbin/
\cp /media/X/TD/IT/IT-SYSTEM/init/RV7.desktop /usr/share/applications
chmod -R 777 /usr/local/rv
/usr/local/rv/rv_linux_register /usr/local/rv/rv.gto
/usr/local/rv/rv_linux_register /home/rv.gto

#Mair 安装后开启Mair  后要指一下mari软件临时目录
/media/Y/BAK-Y/linux_backup/software/Mari/Mari3.3v1-linux-x86-release-64.run --accept-eula --target /usr/local/mari
ln -s /usr/local/mari/mari /usr/local/sbin/
\cp /media/X/TD/IT/IT-SYSTEM/init/Mair3.desktop /usr/share/applications

#houdini
/media/Y/BAK-Y/linux_backup/software/Houdini/houdini-16.0.633-linux_x86_64_gcc4.8/houdini.install --auto-install --install-houdini --install-menus --install-engine-maya --install-bin-symlink --install-hfs-symlink --install-license --accept-EULA
/media/Y/BAK-Y/linux_backup/software/Houdini/houdini-16.5.378-linux_x86_64_gcc4.8/houdini.install --auto-install --install-houdini --install-menus --install-engine-maya --install-bin-symlink --install-hfs-symlink --install-license --accept-EULA
echo 'serverhost=lic.more.com' > /home/render/.sesi_licenses.pref
echo 'serverhost=lic.more.com' > /root/.sesi_licenses.pref
\cp /media/X/TD/IT/IT-SYSTEM/Linux_conf/Houdini_env_py/*.py /opt/hfs16.5.378/houdini/scripts/

#Nuke install 
mkdir -p /usr/local/Nuke10.5v5
mkdir -p /usr/local/Nuke11.1v1
mkdir -p /usr/local/foundry/RLM
cd /media/Y/BAK-Y/linux_backup/software/NUKE/
unzip Nuke10.5v5-linux-x86-release-64-installer -d /usr/local/Nuke10.5v5/
unzip Nuke11.1v1-linux-x86-release-64-installer -d /usr/local/Nuke11.1v1/

# foundry授权
\cp /media/X/TD/IT/IT-SYSTEM/init/foundry_client.lic /usr/local/foundry/RLM

#Deadline
/media/X/TD/Deadline10/install_software/DeadlineClient-10.0.7.0-linux-x64-installer.run --prefix /opt/Thinkbox/Deadline10 --mode unattended --repositorydir /media/X/TD/Deadline10/DeadlineRepository10 --daemonuser render --launcherdaemon True --slavestartup True
\cp /media/X/TD/Deadline10/install_software/LNX/deadline.dll /opt/Thinkbox/Deadline10/bin/
\cp /media/X/TD/Deadline10/install_software/LNX/deadlineslave.exe /opt/Thinkbox/Deadline10/bin/

# 系统优化
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/' /etc/ssh/sshd_config
#加大服务器的文件描述符
echo '*  soft  nofile  1024000' >> /etc/security/limits.conf
echo '*  hard  nofile  1024000' >> /etc/security/limits.conf
echo '*  soft  nproc   1024000' >> /etc/security/limits.conf
echo '*  hard  nproc   1024000' >> /etc/security/limits.conf
echo 'hive  -  nofile  1024000' >> /etc/security/limits.conf
echo 'hive  -  nproc   1024000' >> /etc/security/limits.conf
echo 'ulimit -SHn 65535' >>/etc/rc.local
#用户进程限制
sed -i 's#4096#unlimited#g' /etc/security/limits.d/20-nproc.conf
#调整内核参数文件 /etc/sysctl.conf

cat >> /etc/sysctl.conf << EOF
kernel.pid_max = 65535
#CTCDN系统优化参数
#关闭ipv6节省系统资源
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
#决定检查过期多久邻居条目
net.ipv4.neigh.default.gc_stale_time=120
#使用arp_announce / arp_ignore解决ARP映射问题
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.all.arp_announce=2
net.ipv4.conf.lo.arp_announce=2
# 避免放大攻击
net.ipv4.icmp_echo_ignore_broadcasts = 1
# 开启恶意icmp错误消息保护
net.ipv4.icmp_ignore_bogus_error_responses = 1
#关闭路由转发
net.ipv4.ip_forward = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
#开启反向路径过滤
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
#处理无源路由的包
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
#关闭sysrq功能
kernel.sysrq = 0
#core文件名中添加pid作为扩展名
kernel.core_uses_pid = 1
# 开启SYN洪水攻击保护
net.ipv4.tcp_syncookies = 1
#修改消息队列长度
kernel.msgmnb = 65536
kernel.msgmax = 65536
#设置最大内存共享段大小bytes
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
#timewait的数量，默认180000
net.ipv4.tcp_max_tw_buckets = 6000
net.ipv4.tcp_sack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_rmem = 4096 87380 4194304
net.ipv4.tcp_wmem = 4096 16384 4194304
net.core.wmem_default = 8388608
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
#每个网络接口接收数据包的速率比内核处理这些包的速率快时，允许送到队列的数据包的最大数目
net.core.netdev_max_backlog = 262144
#限制仅仅是为了防止简单的DoS 攻击
net.ipv4.tcp_max_orphans = 3276800
#未收到客户端确认信息的连接请求的最大值
net.ipv4.tcp_max_syn_backlog = 262144
net.ipv4.tcp_timestamps = 0
#内核放弃建立连接之前发送SYNACK 包的数量
net.ipv4.tcp_synack_retries = 1
#内核放弃建立连接之前发送SYN 包的数量
net.ipv4.tcp_syn_retries = 1
#启用timewait 快速回收
net.ipv4.tcp_tw_recycle = 1
#开启重用。允许将TIME-WAIT sockets 重新用于新的TCP 连接
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_mem = 94500000 915000000 927000000
net.ipv4.tcp_fin_timeout = 1
#当keepalive 起用的时候，TCP 发送keepalive 消息的频度。缺省是2 小时
net.ipv4.tcp_keepalive_time = 1800
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_intvl = 15
#允许系统打开的端口范围
net.ipv4.ip_local_port_range = 1024 65000
#修改防火墙表大小，默认65536
net.netfilter.nf_conntrack_max=655350
net.netfilter.nf_conntrack_tcp_timeout_established=1200
# 确保无人能修改路由表
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
EOF
/sbin/sysctl -p
#启动boot过程日志记录
mkdir /var/log/journal
systemd-tmpfiles --create --prefix /var/log/journal
systemctl restart systemd-journald
#core 文件
echo '20 10 * * 1 "find / -name core -print -exec rm -rf {} ;" ' >>/var/spool/cron/root

#systemctl -t service
#systemctl list-unit-files -t service

#关闭不必要的服务
systemctl disable firewalld
systemctl disable postfix
systemctl disable NetworkManager-dispatcher
systemctl disable abrt-ccpp
systemctl disable cups
systemctl disable bluetooth
systemctl disable avahi-daemon
systemctl disable accounts-daemon
systemctl disable atd
systemctl disable ksm
systemctl disable ksmtuned
systemctl disable libvirtd
systemctl disable vmtoolsd
systemctl disable iscsi
systemctl disable iscsid
systemctl disable iscsiuio
systemctl disable wpa_supplicant
systemctl disable kdump

sed -i '/Render_AutoInstall.sh/d' /etc/rc.d/rc.local
